### ISSUE TITLE
Error on HA 2024.1.0b0

### ISSUE THREAD

**Issue by TheFes** [PiotrMachowski/Home-Assistant-custom-components-Custom-Templates#19]
Updating to the new beta causes this issue:

`Setup of package 'integrations' at packages/integrations.yaml, line 1 failed: Integration custom_templates caused error: cannot import name 'TRANSLATION_LOAD_LOCK' from 'homeassistant.helpers.translation' (/usr/src/homeassistant/homeassistant/helpers/translation.py)`

**Comment by Mitch73-2** [comment]
yes i also have this with version :
Core 2024.2.0b1
Supervisor 2024.01.1
Operating System 11.5.rc3
Frontend 20240131.0

`Logger: homeassistant.setup
Source: setup.py:251
First occurred: 17:52:06 (1 occurrences)
Last logged: 17:52:06

Setup failed for custom integration 'custom_templates': Unable to import component: cannot import name 'TRANSLATION_LOAD_LOCK' from 'homeassistant.helpers.translation' (/usr/src/homeassistant/homeassistant/helpers/translation.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/custom_templates/__init__.py", line 11, in <module>
    from homeassistant.helpers.translation import _TranslationCache, TRANSLATION_FLATTEN_CACHE, TRANSLATION_LOAD_LOCK
ImportError: cannot import name 'TRANSLATION_LOAD_LOCK' from 'homeassistant.helpers.translation' (/usr/src/homeassistant/homeassistant/helpers/translation.py)
`

**Comment by PiotrMachowski** [comment]
Fixed in v1.3.0
