### ISSUE TITLE
ct_eval() + config.entity

### ISSUE THREAD

**Issue by ildar170975** [PiotrMachowski/Home-Assistant-custom-components-Custom-Templates#28]
This is rather complex issue - please be patient.
I do not think that this is a bug - and just want to be sure.

Card-mod supports a `config` variable which can be used in templates.

This code gives a fixed "red" row:
```
  - type: entities
    entities:
      - entity: input_boolean.test_boolean
        name: color = fixed red
        card_mod:
          style: |
            :host {
              color: red;
            }
```
![изображение](https://github.com/user-attachments/assets/4633edc7-9b61-473e-b45e-8aae1f7f1316)

This code - colorize a row dependently on the entity:
```
      - entity: input_boolean.test_boolean
        name: color = dynamic
        card_mod:
          style: |
            :host {
              {% if is_state('input_boolean.test_boolean','on') -%}
                {%- set COLOR = 'orange' -%}
              {%- else -%}
                {%- set COLOR = 'cyan' -%}
              {%- endif -%}
              color: {{COLOR}};
            }
```
![изображение](https://github.com/user-attachments/assets/efcc4099-8f89-4e5e-9220-0b41ce6a5ace)

For simplicity - I can use a `config.entity` variable:
```
      - entity: input_boolean.test_boolean
        name: color = dynamic (config.entity)
        card_mod:
          style: |
            :host {
              {% if is_state(config.entity,'on') -%}
                {%- set COLOR = 'orange' -%}
              {%- else -%}
                {%- set COLOR = 'cyan' -%}
              {%- endif -%}
              color: {{COLOR}};
            }
```
![изображение](https://github.com/user-attachments/assets/29270ef2-5fa4-4c65-97ef-9d9fd9f0f45d)

----------------

Now let's check `ct_eval()`.
First with a simple case - a template is a simple fixed string:
```
      - entity: input_boolean.test_boolean
        name: ct_eval('red')
        card_mod:
          style: |
            :host {
              {% set COLOR = 'red'-%}
              color: {{ct_eval(COLOR)}};
            }
```
![изображение](https://github.com/user-attachments/assets/9abb39bd-786b-4d35-a4a0-b93507297ac8)

Next - a template is a complex one:
```
      - entity: input_boolean.test_boolean
        name: ct_eval(template)
        card_mod:
          style: |
            :host {
              {% set TEMPLATE = '{% if is_state("input_boolean.test_boolean","on") -%}
                                 orange
                                 {%- else -%}
                                 cyan
                                 {%- endif %}' -%}
              color: {{ct_eval(TEMPLATE)}};
            }
```
![изображение](https://github.com/user-attachments/assets/381f6e09-5809-42d3-949c-da236a9462d8)

So far `ct_eval()` work OK.

Next - check with `config.entity` variable:
```
      - entity: input_boolean.test_boolean
        name: ct_eval(template with config.entity)
        card_mod:
          style: |
            :host {
              {% set TEMPLATE = '{% if is_state(config.entity,"on") -%}
                                 orange
                                 {%- else -%}
                                 cyan
                                 {%- endif %}' -%}
              color: {{ct_eval(TEMPLATE)}};
            }
```
![изображение](https://github.com/user-attachments/assets/0910c0d3-c2ff-4f71-9a98-a449f7940fee)

It does NOT work - and there are errors in Log:
```
2024-09-20 04:13:06.107 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'config' is undefined when rendering '{% if is_state(config.entity,"on") -%}
orange
{%- else -%}
cyan
{%- endif %}'
2024-09-20 04:13:06.108 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=(:host {
{% set TEMPLATE = '{% if is_state(config.entity,"on") -%}
orange
{%- else -%}
cyan
{%- endif %}' -%}
color: {{ct_eval(TEMPLATE)}};
}) renders=130>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 619, in async_render
render_result = _render_with_context(self.template, compiled, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2654, in _render_with_context
return template.render(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 327, in getattr
value = getattr(obj, attribute)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2686, in _fail_with_undefined_error
return super()._fail_with_undefined_error(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'config' is undefined
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 619, in async_render
render_result = _render_with_context(self.template, compiled, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2654, in _render_with_context
return template.render(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 7, in top-level template code
File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 394, in call
return __context.call(__obj, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/custom_templates/templates/eval_template.py", line 14, in __call__
return tpl.async_render()
^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 621, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'config' is undefined
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 731, in async_render_to_info
render_info._result = self.async_render( # noqa: SLF001
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 621, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TemplateError: UndefinedError: 'config' is undefined
2024-09-20 04:13:06.113 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'config' is undefined when rendering '{% if is_state(config.entity,"on") -%}
orange
{%- else -%}
cyan
{%- endif %}'
```
Seems that `ct_eval()` cannot render `config.entity`.
Is this happening because `ct_eval()` works on a server side which does not know about `config` variable?

**Comment by ildar170975** [comment]
Full code of the card used for demonstration:
```
    type: entities
    entities:
      - entity: input_boolean.test_boolean
        name: color = fixed red
        card_mod:
          style: |
            :host {
              color: red;
            }
      - entity: input_boolean.test_boolean
        name: color = dynamic
        card_mod:
          style: |
            :host {
              {% if is_state('input_boolean.test_boolean','on') -%}
                {%- set COLOR = 'orange' -%}
              {%- else -%}
                {%- set COLOR = 'cyan' -%}
              {%- endif -%}
              color: {{COLOR}};
            }
      - entity: input_boolean.test_boolean
        name: color = dynamic (config.entity)
        card_mod:
          style: |
            :host {
              {% if is_state(config.entity,'on') -%}
                {%- set COLOR = 'orange' -%}
              {%- else -%}
                {%- set COLOR = 'cyan' -%}
              {%- endif -%}
              color: {{COLOR}};
            }
      - type: section
        label: using ct_eval()
      - entity: input_boolean.test_boolean
        name: ct_eval('red')
        card_mod:
          style: |
            :host {
              {% set COLOR = 'red'-%}
              color: {{ct_eval(COLOR)}};
            }
      - entity: input_boolean.test_boolean
        name: ct_eval(template)
        card_mod:
          style: |
            :host {
              {% set TEMPLATE = '{% if is_state("input_boolean.test_boolean","on") -%}
                                 orange
                                 {%- else -%}
                                 cyan
                                 {%- endif %}' -%}
              color: {{ct_eval(TEMPLATE)}};
            }
      - entity: input_boolean.test_boolean
        name: ct_eval(template with config.entity)
        card_mod:
          style: |
            :host {
              {% set TEMPLATE = '{% if is_state(config.entity,"on") -%}
                                 orange
                                 {%- else -%}
                                 cyan
                                 {%- endif %}' -%}
              color: {{ct_eval(TEMPLATE)}};
            }
```

**Comment by PiotrMachowski** [comment]
Ok, the problem is that `ct_eval` doesn't pass the whole current context during the evaluation of the template passed in text.

Could you please describe the actual case you want to use it for?

**Comment by ildar170975** [comment]
My 1st post contains a simplified description of the issue.
Here is a possible real-life use-case: 

Consider this code:
```
- entity: SOME_ENTITY
  card_mod:
    style:
      {% set SPEED = ... -%}
      ... set "rotation" animation dependently on some "SPEED" value: higher -> faster, lower -> slower
```
where `SPEED` may be defined as
```
  card_mod:
    style:
      {% set SPEED = states(SOME_ENTITY) -%}
      ...
```
or
```
  card_mod:
    style:
      {% set SPEED = state_attr(SOME_ENTITY, SOME_ATTR) -%}
      ...
```
So far `ct_eval()` is not needed.

But assume that a whole `card_mod` part can be re-usable: since it may contain lots of styles - I would try to place it into some separate yaml and then call it:
```
card_mod: !include /config/.../my_super_style.yaml
```
In this case I would want to exclude a particular definition of the `SPEED` variable for that reusable code:
```
- entity: SOME_ENTITY
  SPEED: >
    {{ states(SOME_ENTITY) }}
  card_mod: !include /config/.../my_super_style.yaml
```
where that included yaml file contains smth like:
```
style:
  ... use ct_eval(config.SPEED)
  ... set rotation dependently on that "SPEED" value
```
i.e. in another card for another entity I will use
```
- entity: SOME_ENTITY
  SPEED: >
    {{ state_attr(SOME_ENTITY,SOME_ATTR) }}
  card_mod: !include /config/.../my_super_style.yaml
```
It is a known fact that we can use `config` variable inside card-mod code - and we can add and then use USER-DEFINED options like `SPEED` as well (see one more simplified example in the end of his post).

So far `ct_eval()` works FINE.

But it stops working here:
```
- entity: SOME_ENTITY
  SPEED: >
    {{ state_attr(config.entity,SOME_ATTR) }}
  card_mod: !include /config/.../my_super_style.yaml
```
i.e. when `config.entity` is used.

----------

Simplified example with using `config` variable with `ct_eval()`:
```
type: entities
entities:
  - entity: input_boolean.test_boolean
    name: ct_eval(template with entity)
    TEMPLATE: >-
      {% if is_state("input_boolean.test_boolean","on") -%}
      orange
      {%- else -%}
      cyan
      {%- endif %}
    card_mod:
      style: |
        :host {
          color: {{ct_eval(config.TEMPLATE)}};
        }
  - entity: input_boolean.test_boolean
    name: ct_eval(template with config.entity)
    TEMPLATE: >-
      {% if is_state(config.entity,"on") -%}
      orange
      {%- else -%}
      cyan
      {%- endif %}
    card_mod:
      style: |
        :host {
          color: {{ct_eval(config.TEMPLATE)}};
        }
```
![изображение](https://github.com/user-attachments/assets/69bbed16-98ce-491b-b599-28ff7f452d23)

**Comment by PiotrMachowski** [comment]
Thank you for your explanation. This functionality should work in [v1.4.1](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Custom-Templates/releases/tag/v1.4.1).

This was a nice improvement, thank you!

**Comment by ildar170975** [comment]
Piotr, this is magnificent and super fast )))
Thanks a lot!!!!
Will test it soon.

**Comment by PiotrMachowski** [comment]
I have also added the following functionality:
```
{% set foo = "FOO" %}
{{ ct_eval("{{ foo + bar }}", variables={"bar": "BAR"}) }}
```
Result:
```
FOOBAR
```

**Comment by ildar170975** [comment]
I see, will test this new "variables" functionality in 10 days, leaving today for a next shift...
Keep making this world better!

**Comment by ildar170975** [comment]
Processing `config.entity` in `ct_eval()` - DOES WORK !

**Comment by PiotrMachowski** [comment]
Great, thank you!
